<?php

use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Field\BaseFieldDefinition;

/**
 * Implements hook_entity_base_field_info().
 */
function pubkey_encrypt_entity_base_field_info(EntityTypeInterface $entity_type) {
  $fields = array();

  //Register additional base fields with the user entity.
  if ($entity_type->id() === 'user') {
    $fields['pkey_protected'] = BaseFieldDefinition::create('boolean')
      ->setLabel(t('Is Private key protected?'))
      ->setDescription(t('Tells whether the Private key of a user has been protected or not.'))
      ->setTranslatable(TRUE)
      ->setDefaultValue(0);

    $fields['pubkey'] = BaseFieldDefinition::create('string')
      ->setLabel(t('Public key'))
      ->setDescription(t('Public key associated with the user.'))
      ->setSettings(array(
        'default_value' => '',
      ))
      ->setTranslatable(FALSE);

    $fields['privkey'] = BaseFieldDefinition::create('string')
      ->setLabel(t('Private key'))
      ->setDescription(t('Private key associated with the user.'))
      ->setSettings(array(
        'default_value' => '',
      ))
      ->setTranslatable(FALSE);
  }

  return $fields;
}
